# Site settings
title: Ustun Ozgur Software Engineering Blog
email: ustun@ustunozgur.com
description: > # this means to ignore newlines until "baseurl:"
  Ustun Ozgur Software - We build beautiful products that work. We are experts in Python, JavaScript and Clojure. We specialize in Django and React.js.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ustunozgur.com" # the base hostname & protocol for your site
twitter_username: ustunozgur
github_username:  ustun

# Build settings
markdown: kramdown
